### ISSUE TITLE
Do you do any more work on 3LAS?

### ISSUE THREAD

**Issue by linuxdevel** [JoJoBond/3LAS#1]
I'm trying to find a low latency audio system to send audio from a shortwave radio through raspberry PI (With external sound card) to a webbrowser (Chrome), and came across 3LAS. It looks interesting and Im about to test it. But I see that there has not been done any work on this project for a long time. 
Is it a dead end to use this one? Maybe someone else have similar javascript based solution?

Concerning the audio link, only low bitrate is needed in my case. (for SSB on short wave, a max of approximately 3kb audio bandwith should be enough, thus ~8kbit sampling rate should be good.

Br

**Comment by JoJoBond** [comment]
Hi,
thank you for you interest in my project.

I'm currently not actively working on 3LAS, since it has proven to be quite stable.
I use it in a production environment as simultaneous translation system for smartphones via WiFi.

I think I have some slight modifications on my production machine that I have to push to git.

Basically what you can do with it, is to push audio data to a browser on a broad range of devices (smartphones, pc, tablet, smartTVs). The data needs to be either mp3 or wav. Ogg (Vorbis&Opus) is not completely implemented and needs some work. I use mp3 as a primary source and wav as a fallback. The total lag is a little less than 1 sec.
I use ffmpeg to convert the audio into the right format, so as long as you can get your audio into ffmpeg, you should be able to use 3LAS.

I don't have my production machine at my place, but will be able to check on it on Saturday or Sunday.
You should however be able to use the code as is, and then replace it with my last version later, without problems.

**Comment by linuxdevel** [comment]
Hi
Thanks alot for quick reply. And thank you for eventually checking in the modifications when you get a chance!
I will give it a try, and keep you posted on progress :) Eventually, if it works withouth too much latency  it will be used together with wizkers radio: http://www.wizkers.io/wizkersradio to send audio from connected receiver to the client. Low-latency is a must, because you want almost real-time feedback when radio settings is changed. There is a windows application that handles low latency transmission very good (remaudio), however, a general solution in javascript/node would be so much better :)

Br
linuxdevel

**Comment by JoJoBond** [comment]
Naturally latency with mp3 will be higher, due to the overlapping frames used in encoding. Mp3 will lag behind half a frame length in comparison to wav. If you plan to have a low bandwith audio anyway, you might just aswell skip mp3 fully and only use wav.

**Comment by JoJoBond** [comment]
I updated the codebase with my current production code. This mainly affected ogg support which is still not usable. Wav and mp3 should be fine though.

**Comment by linuxdevel** [comment]
@JoJoBond Thanks, sorry for late feedback. I havent had the chance to test it out properly yet. But hopefully soon. 
Br

**Comment by JoJoBond** [comment]
No problem.
If you have questions or need some assistence, just let me know.
