### ISSUE TITLE
Sorry.. help me

### ISSUE THREAD

**Issue by deokju** [JoJoBond/3LAS#10]
hi JoJoBond.

I'm use WAV Stream player and mpeg player.
so....
What mean is TotalBatchSampleSize, TotalBatchByteSize?

**Comment by JoJoBond** [comment]
For WAV the continuous stream of sample data is split up into blocks of [TotalBatchSampleSize] samples. Depending on the number of channels and the bit-depth, this results in a data block with a size of [TotalBatchByteSize] bytes (this is payload only, NOT including the header).
All of this is derived from the [BatchDuration] parameter (measured in seconds, so that it is independent of the sample rate).

**Comment by deokju** [comment]
thank you very much.
