### ISSUE TITLE
It is limited to the iPhone. No music plays during a call.

### ISSUE THREAD

**Issue by deokju** [JoJoBond/3LAS#14]
Android works without any problems.
The current situation is as follows.
1.You are calling.
2.Start streaming using the button on the screen.
  Current time get Web Audio Context
3.call end.
4. 3las play streaming sound.
I expect it to be streaming. But there is no sound.

**Comment by JoJoBond** [comment]
You mean a phone call on the smartphone while the stream is running?

**Comment by deokju** [comment]
No...
You say mean...
step1. Start streaming.
step2. call is running.

I say mean...
step1.  call is running.
step2.  Start streaming.

**Comment by JoJoBond** [comment]
Either way, iOS is weird when it comes to JavaScript execution. As far as I can tell, JavaScript will only be executed as long as you keep viewing the browser app. As far as I can tell, there is nothing you can do about that. Phone calls might also have exclusive access to microphone and speakers, so that could also be an issue.

**Comment by deokju** [comment]
ok. I unserstand.
Thank you for always kindly responding.
Thank you very much  X 1000
