### ISSUE TITLE
Latency ? iOS vs Android

### ISSUE THREAD

**Issue by maathor** [JoJoBond/3LAS#8]
Hi,

How many latency do you get ? In mp3 encoding, I got something very "real time" with an iOS (iPhone 6).
With an HTC One, Galaxy S7 or cheap Android, I always have, something like 400/500ms latency.
Do you have any idea to decrease this latency ?

Thanks you a lot for your hard and good work,

Marc

**Comment by JoJoBond** [comment]
Mp3 will have a have a minimum delay of 576 samples plus encoding, decoding and network times. You can lower the delay by increasing the sample rate, since the frame size is fixed (frames will fill in shorter time -> less delay). You can try to lower the "this.UseFrames" and "this.WindowSize " in "mpeg.js". Make sure that WindowSize > UseFrames, and test it with your target devices. Also try different browsers, at least on the Android devices. There is no need to try different browsers on iOS as they all use the same browser engine anyway (at least since v9.xx - I think).

If low delay is super critical you can try using wav. With wav you can get rid of the delay added by the windowing and framing in mp3.

Hope that helps.

If you have further questions, don't hesitate to ask.
